#------Problem 2 @ Project Euler------#
"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

def even_fibonacci_numbers():
    fibnums = []
    evensums = []
    x = 1
    y = 2
    fibnums.append(x)
    fibnums.append(y)
    while fibnums[-1] <= 4000000:
        f = fibnums[-1] + fibnums[-2]
        fibnums.append(f)
    for x in fibnums:
        if x % 2 == 0:
            evensums.append(x)
    print(sum(evensums))
even_fibonacci_numbers()
